apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-app
  labels:
    app: book-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service-app
  template:
    metadata:
      labels:
        app: book-service-app
    spec:
      containers:
        - name: book-service-app
          image: ecco18/book-service:v7
          env:
            - name: DATABASE_USERNAME
              value: "database_username"
            - name: DATABASE_PASSWORD
              value: "database_password"
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  labels:
    monitor: book-service
  name: book-app-service
spec:
  selector:
    app: book-service-app
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: book-nodeport-service
spec:
  type: NodePort
  selector:
    app: book-service-app
  ports:
    - protocol: TCP
      nodePort: 30083
      port: 8082